### ISSUE TITLE
环境变量制品构建报错

### ISSUE THREAD

**Issue by ulswww** [gokins-main/gokins#33]
```
version: 1.0
vars:          
stages:        
  - stage: 
    name: artifactStage     
    displayName: artifactStage
    steps:
      - step: shell@sh       
        name: artifactStep          
        displayName: artifactStep
        env:   
        commands:
          - export hello="hello world"   
        artifacts:          
          - scope: var    
            name: hello   
```
搞错：
![image](https://github.com/gokins/gokins/assets/5510787/6f58d1c7-7f98-4edc-a65f-62f8011520bf)
